services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: prova_mestre
      POSTGRES_PASSWORD: prova_mestre
      POSTGRES_DB: prova_mestre
    ports:
      - "5432:5432"
    volumes:
      - prova_mestre_db_data:/var/lib/postgresql/data

volumes:
  prova_mestre_db_data:
